{{- if .Values.operator.rawObjects.allowlist }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jinja-template-operator.fullname" . }}-raw-object-allowlist
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jinja-template-operator.labels" . | nindent 4 }}
data:
  allowlist.yaml: |
    {{- toYaml .Values.operator.rawObjects.allowlist | nindent 4 }}
{{- end }}
